name: 'Calibre-Web Smoke test with IIAB install'

on: [push, pull_request, workflow_dispatch]

jobs:
  test-install:
    runs-on: ubuntu-24.04
    steps:
      - name: Clean clone to /opt/iiab/iiab (chmod permissions preserved)
        run: |
          sudo git clone https://github.com/iiab/iiab    # in $GITHUB_WORKSPACE == /home/runner/work/calibre-web/calibre-web
          sudo mkdir /opt/iiab
          sudo mv iiab /opt/iiab
      - name: Set up /etc/iiab/local_vars.yml
        run: |
          echo "calibreweb_install: True" > local_vars.yml    # in $GITHUB_WORKSPACE == /home/runner/work/calibre-web/calibre-web
          echo "calibreweb_enabled: True" >> local_vars.yml
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "calibreweb_repo_url: $GITHUB_SERVER_URL/${{ github.event.pull_request.head.repo.owner.login }}/${{ github.event.repository.name }}" >> local_vars.yml
            echo "calibreweb_version: $GITHUB_HEAD_REF" >> local_vars.yml
          else # works for both push and workflow_dispatch
            echo "calibreweb_repo_url: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY" >> local_vars.yml
            echo "calibreweb_version: $GITHUB_REF_NAME" >> local_vars.yml
          fi
          cat >> local_vars.yml << EOF
          nodocs: True
          kolibri_install: False
          kolibri_enabled: False
          kiwix_install: False
          kiwix_enabled: False
          osm_vector_maps_install: False
          awstats_install: False
          awstats_enabled: False
          matomo_install: False
          matomo_enabled: False
          captiveportal_install: False
          network_install: False
          network_enabled: False
          admin_console_install: False
          admin_console_enabled: False
          EOF
          sudo mkdir /etc/iiab
          sudo mv local_vars.yml /etc/iiab
          cat /etc/iiab/local_vars.yml
      - run: sudo /opt/iiab/iiab/scripts/ansible    # Install Ansible
      - run: sudo ./iiab-install                    # Install IIAB!
        working-directory: /opt/iiab/iiab/
      - name: Install Firefox
        uses: browser-actions/setup-firefox@v1
      - run: firefox --version
      - name: Create Python environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
      - name: Install Python dependencies for testing
        uses: py-actions/py-dependency-install@v4
        with:
          path: /usr/local/calibre-web-py3/integration-tests-requirements.txt
      - name: Execute Integration Tests for Firefox
        # Note that there are issues with creating the cache path for pytest, which results in the below warning.
        # PytestCacheWarning: could not create cache path /usr/local/calibre-web-py3/.pytest_cache/v/cache/nodeids: [Errno 13] Permission denied: '/usr/local/calibre-web-py3/pytest-cache-files-su2iy_u0'
        # The tests pass, and -p no:cacheprovider makes it so the warning is not displayed
        run: pytest -s --splinter-webdriver firefox --splinter-headless
        working-directory: /usr/local/calibre-web-py3
