name: Integration tests
run-name: Integration tests
on: [push]
jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
      - run: chrome --version
      - name: Install Firefox
        uses: browser-actions/setup-firefox@v1
      - run: firefox --version
      - name: Create Python environment
        run: |
          python3 -m venv calibre-web-env
          source calibre-web-env/bin/activate
      - name: Install Python dependencies for testing
        uses: py-actions/py-dependency-install@v4
        with:
          path: requirements.txt
      - name: Download dummy database
        run: wget -O app.db https://github.com/iiab/iiab/raw/refs/heads/master/roles/calibre-web/files/app.db
      - name: Execute Calibre-Web in background
        run: nohup python3 cps.py &
      - name: Verify local website
        run: curl -L localhost:8083
      - name: Install Python dependencies for testing
        uses: py-actions/py-dependency-install@v4
        with:
          path: integration-tests-requirements.txt
      - name: Execute Integration Tests for Chrome
        run: pytest -s --splinter-webdriver chrome --splinter-headless
      - name: Execute Integration Tests for Firefox
        run: pytest -s --splinter-webdriver firefox --splinter-headless
