name: 'Calibre-Web Smoke test with IIAB install'

on: [push, pull_request, workflow_dispatch]

jobs:
  test-install:
    runs-on: ubuntu-24.04
    steps:
      - name: Set up /opt/iiab/iiab
        run: |
          mkdir -p /opt/iiab/iiab/
          sudo git clone https://github.com/iiab/iiab /opt/iiab/iiab/
          sudo chown runner /opt/iiab/iiab
          sudo chmod 600 /opt/iiab/iiab/
      - name: Set up /etc/iiab/local_vars.yml
        run: |
          sudo mkdir /etc/iiab
          sudo curl https://raw.githubusercontent.com/iiab/calibre-web/master/scripts/omg.yml > $GITHUB_WORKSPACE/local_vars.yml
          sudo cp $GITHUB_WORKSPACE/local_vars.yml /etc/iiab/local_vars.yml
      - run: sudo /opt/iiab/iiab/scripts/ansible    # Install Ansible
      - run: sudo ./iiab-install                    # Install IIAB!
        working-directory: /opt/iiab/iiab/
