name: 'Calibre-Web Smoke test with IIAB install'

on: [push, pull_request, workflow_dispatch]

jobs:
  test-install:
    runs-on: ubuntu-24.04
    steps:
      - name: Set up /opt/iiab/iiab
        run: |
          sudo mkdir -p /opt/iiab/
      - name: Clone repo
        run: sudo git clone https://github.com/iiab/iiab
        working-directory: /opt/iiab/
      - name: Set proper permissions
        # If you don't do this, then ./iiab-install fails because of /opt/iiab/iiab being a world writable directory
        run: sudo chmod 755 /opt/iiab/iiab
      - name: Set up /etc/iiab/local_vars.yml
        run: |
          sudo mkdir /etc/iiab
          sudo curl https://raw.githubusercontent.com/iiab/calibre-web/master/scripts/omg.yml > $GITHUB_WORKSPACE/local_vars.yml
          sudo cp $GITHUB_WORKSPACE/local_vars.yml /etc/iiab/local_vars.yml
      - run: sudo /opt/iiab/iiab/scripts/ansible    # Install Ansible
      - run: sudo ./iiab-install                    # Install IIAB!
        working-directory: /opt/iiab/iiab/
