name: 'Calibre-Web Smoke test with IIAB install'

on: [push, pull_request, workflow_dispatch]

jobs:
  test-install:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0    # Default is 1, but iiab-summary (below) needs git tag history.
      - name: Set up /opt/iiab/iiab
        run: |
          mkdir /opt/iiab
          mv $GITHUB_WORKSPACE /opt/iiab
          # Github Actions is weird, do not delete the line below. Yes, it will cause everything to break. Really.
          mkdir $GITHUB_WORKSPACE
      - name: Set up /etc/iiab/local_vars.yml
        run: |
          sudo mkdir /etc/iiab
          sudo curl https://raw.githubusercontent.com/iiab/calibre-web/master/scripts/omg.yml > $GITHUB_WORKSPACE/local_vars.yml
          sudo cp $GITHUB_WORKSPACE/local_vars.yml /etc/iiab/local_vars.yml
      - run: ls /opt/iiab/iiab/scrips/
      - run: sudo /opt/iiab/iiab/scripts/ansible    # Install Ansible
      - run: sudo ./iiab-install                    # Install IIAB!
        working-directory: /opt/iiab/iiab
